apiVersion: v1
kind: Service
metadata:
  name: gogs
  labels:
    app: gogs
    group: devops    
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 22
    protocol: TCP
    port: 3000
    protocol: TCP    
  selector:
    app: gogs
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
        group: devops
        tier: frontend
    spec:
      containers:
      - name: gogs
        image: gogs/gogs
        ports:
        - containerPort: 22
          name: gogs-ssh
          containerPort: 3000
          name: gogs-ui