apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
    group: devops    
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: jenkins
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        group: devops
        tier: frontend
    spec:
      containers:
      - name: jenkins
        image: jenkinsci/blueocean
        ports:
        - containerPort: 8080
          name: jenkins
